# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /kkb-server-demo
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.kkb.hk.entity
  # 配置mapper的扫描，找到所有的.xml映射文件
  mapperLocations: classpath:mapper/*.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# Spring配置
spring:
  profiles:
    #druid：测试环境  rel：预发环境  prod:生产环境
    active: druid

# 日志配置
logging:
  level:
    com.kkb.hk: debug
    org.springframework: warn